### ISSUE TITLE
File names a bit too hardcoded

### ISSUE THREAD

**Issue by etm** [jrobertson/rss_creator#1]
hi j,

```ruby
  rss = RSScreator.new File.join(__dir__,'list.rss')
  ...
  rss.save
```

gives me list.rss, feed.json, feed.xml. I think the later two should be named list.json and list.xml. And it would be nice to be able to select which of the three ones i am creating.

best,

eTM

**Comment by jrobertson** [comment]
Hi eTM,

I have addressed the issue raised and now the gem only produces the RSS file by default. Let me know when this is working for you and I will close this issue.

Best regards,

James

**Comment by etm** [comment]
Yes, thanks. Keep up the good work!
